
```{r}
vector1 = c("A", "B", "C", "D")
vector2 =  c(1, 2, 3, 4)

data_frame_variable = data.frame(alphabets = vector1,
                                 numbers = vector2,
                                 words = c("AAA", "BBB", "CCC", "DDD"),
                                 row.names = c("r1", "r2", "r3", "r4")
)
```

### Accessing Data

#### Access by Column

```{r}
data_frame_variable[, 1]
data_frame_variable$alphabets
```

#### Access by Row

```{r}
data_frame_variable[1 ,]
```

#### Get Column Names

```{r}
col_names = colnames(data_frame_variable)
```

#### Get Row Names

```{r}
row_names = rownames(data_frame_variable)
```

### Excluding Columns

#### Exclude the First Column

```{r}
data_frame_variable[, -1]
```

#### Exclude the First and Third Columns

```{r}
data_frame_variable[, -c(1, 3)]
```

This notebook demonstrates how to access and exclude columns and rows in a data frame in R.
```

When you save and render this `.Rmd` file, it will generate an HTML notebook with the code and corresponding outputs.